import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useEffect } from "react";
import Features from "~/components/home/Features";
import FeaturesBlocks from "~/components/home/FeaturesBlocks";
import Footer from "~/components/home/Footer";
import Header from "~/components/home/Header";
import HeroHome from "~/components/home/HeroHome";
import Testimonials from "~/components/home/Testimonials";
import AOS from "aos";
import "aos/dist/aos.css";

export default function Home() {
  useEffect(() => {
    AOS.init({
      once: true,
      disable: "phone",
      duration: 700,
      easing: "ease-out-cubic",
    });
  });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col overflow-hidden">
        {/*  Site header */}
        <Header />

        {/*  Page content */}
        <main className="flex-grow text-zinc-900">
          {/*  Page sections */}
          <HeroHome />
          <Features />
          {/* <FeaturesBlocks /> */}
          {/* <Testimonials /> */}
        </main>

        {/*  Site footer */}
        <Footer />
      </div>
    </>
  );
}
